services:
  llama-server:
    image: ghcr.io/ggml-org/llama.cpp:server
    container_name: llama-server
    ports:
      - "127.0.0.1:8889:8080"
    expose:
      - "8080"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./models:/models
      - './aitech.jinja:/app/aitechV3.jinja'
    # Мы объединяем проверку, скачивание и запуск в одну команду
    entrypoint: >
      sh -c "
      MODEL_PATH=\"/models/$$MODEL_NAME\";
      if [ ! -f \"$$MODEL_PATH\" ] || [ $$(stat -c%s \"$$MODEL_PATH\") -lt 1000000 ]; then
        echo 'Модель не найдена или битая. Начинаю загрузку...';
        apt-get update && apt-get install -y curl;
        curl -L $$DONLOAD_URL -o \"$$MODEL_PATH\";
        echo 'Загрузка завершена!';
      else
        echo 'Модель найдена, запускаю сервер...';
      fi;
      exec /app/llama-server -m \"$$MODEL_PATH\"  --mmproj \"/models/mmproj-F16.gguf\" --embeddings  --host 0.0.0.0 --port 8080 -t 8 -c 131072 -b 512 -ub 256 -fa on --mlock --context-shift --swa-full -np 6 --cache-prompt --cache-ram 16384 --lookup-cache-dynamic /models/lookup_cache.bin --reasoning off --jinja

      "
    restart: unless-stopped
